#include "userButton.h"
#include "stm32f10x.h"

void EXTI15_10_IRQHandler(void) {
		GPIOA->BSRR = 0X00000020;
    // Check if the interrupt is generated by Line 13 (PC13)
		if ((EXTI->PR & EXTI_PR_PR13) != 0) {
				
				
        // Clear the pending interrupt for Line 13
        EXTI->PR |= EXTI_PR_PR13;
    }
    
}

void setup_user_button(void){
	// Enable the GPIOC & AFIO clocks
	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;

	// REMOVE
	// Configure PA5 (alternate function, push-pull, max speed 50 MHz)
	GPIOA->CRL |= GPIO_CRL_MODE5;
  GPIOA->CRL &= ~GPIO_CRL_CNF5;
	
	// Configure PC13 as input with pull-up
	GPIOC->CRH &= ~GPIO_CRH_CNF13;  // Clear CNF bits
	GPIOC->CRH |= GPIO_CRH_CNF13_1; // Input mode with pull-up/pull-down
	GPIOC->BSRR = GPIO_BSRR_BS13;   // Set bit 13 to enable pull-up

	// Configure EXTI Line 13
	AFIO->EXTICR[3] &= ~AFIO_EXTICR4_EXTI13; // Clear EXTI13 bits
	AFIO->EXTICR[3] |= AFIO_EXTICR4_EXTI13_PC; // Set EXTI13 to connect to Port C

	EXTI->IMR |= EXTI_IMR_MR13; // Enable interrupt on Line 13
	EXTI->FTSR |= EXTI_FTSR_TR13; // Falling edge trigger

	// Enable the EXTI Line 15-10 interrupt
	NVIC_EnableIRQ(EXTI15_10_IRQn);
}
